name: E2E-testing

on:
  pull_request:
  push:
    branches:
      - 'renovate/**'

jobs:
  e2e:
    env:
      NODE_ENV: test
      NEXT_PUBLIC_SITE_ENV: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install deps (with cache)
        run: pnpm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Build
        run: pnpm build

      - name: e2e test
        run: pnpm test:start

      - name: Unit test
        run: pnpm test:unit

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test results
          path: |
            playwright/test-results
